In [2]:
import pandas as pd

In [5]:
years = range(2011, (2016 + 1)) # 2006 to 2016

In [19]:
world_gdp_df_raw = pd.read_csv("./gdp_from_world_bank/API_NY.GDP.PCAP.CD_DS2_en_csv_v2.csv", skiprows=4)

keep_columns = ['Country Name', 'Country Code'] + map(str, years)
# print(keep_columns)
world_gdp_df_raw = world_gdp_df_raw[keep_columns]

world_gdp_df_raw.head()

,Country Name,Country Code,2011,2012,2013,2014,2015,2016
0,Aruba,ABW,25324.720362,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,603.537023,669.009051,631.744971,612.069651,584.025902,561.778746
2,Angola,AGO,4299.012889,4598.249988,4804.616884,4709.312024,3695.793748,3110.808183
3,Albania,ALB,4437.178068,4247.614308,4414.723140,4575.763787,3954.022783,4146.896250
4,Andorra,AND,40919.183279,38167.095746,40215.435317,NaN,NaN,NaN

In [20]:
world_gdp_df = pd.melt(world_gdp_df_raw, id_vars=['Country Name', 'Country Code'],
                       var_name='Year', value_name='GDP')

world_gdp_df.head()

  Country Name Country Code  Year           GDP
0        Aruba          ABW  2011  25324.720362
1  Afghanistan          AFG  2011    603.537023
2       Angola          AGO  2011   4299.012889
3      Albania          ALB  2011   4437.178068
4      Andorra          AND  2011  40919.183279

## Same for economic freedom

In [8]:
economic_freedom_raw_df = pd.read_csv("./frazer_institute_economic_freedom/economic-freedom-of-the-world-data-for-researchers.csv")

In [9]:
economic_freedom_raw_df["Year"].unique()

array([2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004,
       2003, 2002, 2001, 2000, 1995, 1990, 1985, 1980, 1975, 1970])

In [10]:
economic_freedom_raw_df[economic_freedom_raw_df["Year"] == years[0]]

,Year,ISO_Code,Countries,Economic Freedom Summary Index,Government Consumption,1A data,Transfers and subsidies,1B data,Government enterprises and investment,1C data,...,Conscription,Labor market regulations,Administrative requirements,Bureaucracy costs,Starting a business,Extra payments/bribes/favoritism,Licensing restrictions,Tax compliance,Business regulations,Regulation
477,2011,HKG,Hong Kong,8.91,8.21,12.10,9.52,2.27,8.0,15.40,...,10.0,9.29,6.67,3.05,9.88,7.93,9.80,9.13,7.74,9.01
478,2011,SGP,Singapore,8.66,5.65,20.80,10.00,0.03,7.0,NaN,...,0.0,7.70,7.61,2.15,9.90,8.98,9.97,9.08,7.95,8.55
479,2011,CHE,Switzerland,8.23,7.00,16.20,6.00,15.18,10.0,13.20,...,5.0,8.41,5.49,1.48,9.32,8.32,8.34,9.29,7.04,8.26
480,2011,NZL,New Zealand,8.15,4.35,25.20,2.78,26.99,8.0,16.72,...,10.0,8.66,5.56,2.04,9.96,9.17,9.41,8.30,7.41,8.19
481,2011,ARE,Unit. Arab Em.,8.06,8.01,12.75,9.22,3.37,4.0,34.73,...,10.0,8.51,6.37,2.98,9.68,8.62,9.98,9.87,7.92,8.25
482,2011,MUS,Mauritius,8.00,7.21,15.50,8.47,6.10,7.0,23.32,...,10.0,7.68,4.50,4.67,9.77,5.84,8.54,8.20,6.92,8.11
483,2011,CHL,Chile,7.94,6.94,16.40,8.04,7.68,10.0,9.40,...,1.0,6.27,4.89,3.82,9.70,7.55,8.27,6.74,6.83,7.48
484,2011,AUS,Australia,7.93,4.44,24.90,6.86,12.03,10.0,12.69,...,10.0,7.27,3.43,1.95,9.93,7.65,9.07,8.78,6.80,7.85
485,2011,CAN,Canada,7.87,3.76,27.20,7.05,11.33,8.0,18.12,...,10.0,8.54,4.10,2.02,9.84,7.90,8.14,8.53,6.75,8.27
486,2011,GBR,United Kingdom,7.81,4.18,25.80,5.73,16.17,8.0,16.59,...,10.0,8.27,3.95,1.90,9.58,7.84,9.19,8.77,6.87,7.60
487,2011,FIN,Finland,7.80,2.82,30.40,3.76,23.39,8.0,17.08,...,3.0,5.57,6.31,1.52,9.52,8.99,9.76,8.96,7.51,7.67
488,2011,JOR,Jordan,7.77,5.09,22.70,7.41,9.99,8.0,18.20,...,10.0,8.44,4.41,4.83,9.47,6.00,8.82,8.31,6.97,7.98
489,2011,BHR,Bahrain,7.76,4.06,26.20,9.30,3.06,4.0,NaN,...,10.0,8.90,6.31,3.25,8.95,7.64,9.98,9.60,7.62,8.71
490,2011,IRL,Ireland,7.75,3.53,28.00,5.31,17.73,8.0,16.17,...,10.0,8.12,4.59,2.44,9.68,8.03,7.24,9.10,6.85,7.32
491,2011,ARM,Armenia,7.71,7.83,13.38,8.09,7.53,10.0,13.50,...,0.0,6.66,4.68,6.08,9.72,4.32,9.57,5.74,6.69,7.46
492,2011,USA,United States,7.70,6.03,19.50,5.77,16.01,7.0,21.21,...,10.0,9.01,3.88,2.59,9.79,5.97,9.97,8.04,6.71,7.93
493,2011,CYP,Cyprus,7.69,4.98,23.08,6.02,15.10,10.0,3.07,...,0.0,6.10,5.12,3.71,9.61,6.00,4.91,8.35,6.28,7.06
494,2011,EST,Estonia,7.68,3.63,27.64,6.24,14.31,8.0,19.42,...,3.0,6.17,5.48,3.33,9.69,7.16,8.48,9.05,7.19,7.79
495,2011,TWN,Taiwan,7.67,5.37,21.75,9.26,3.20,7.0,23.89,...,3.0,4.97,5.82,3.43,9.65,6.67,9.36,7.52,7.08,6.91
496,2011,MLT,Malta,7.65,4.24,25.60,6.07,14.91,6.0,NaN,...,10.0,7.16,3.34,4.30,8.62,5.41,6.61,8.44,6.12,7.53
497,2011,DNK,Denmark,7.64,1.26,35.70,4.37,21.15,8.0,18.28,...,3.0,7.36,4.01,1.86,9.73,8.56,9.71,8.54,7.07,8.05
498,2011,GEO,Georgia,7.62,5.91,19.90,7.14,10.98,4.0,34.10,...,1.0,7.03,5.92,6.35,9.90,7.07,9.68,6.86,7.63,8.12
499,2011,CRI,Costa Rica,7.61,5.38,21.70,9.43,2.60,10.0,9.47,...,10.0,6.27,3.58,4.59,7.96,5.34,8.03,7.47,6.16,6.57
500,2011,DEU,Germany,7.60,4.38,25.10,2.56,27.79,10.0,11.31,...,10.0,6.34,3.97,1.45,9.47,7.78,9.25,7.68,6.60,7.07
501,2011,PER,Peru,7.59,7.68,13.90,9.56,2.12,7.0,20.10,...,10.0,7.02,2.80,5.03,9.06,4.56,7.98,6.72,6.02,7.46
502,2011,AUT,Austria,7.57,4.21,25.70,3.35,24.91,10.0,13.27,...,3.0,6.29,3.79,1.45,8.99,7.01,7.65,8.09,6.16,7.17
503,2011,NLD,Netherlands,7.51,0.50,38.30,3.06,25.97,8.0,19.72,...,10.0,6.77,4.83,1.57,9.62,8.38,8.18,8.58,6.86,7.52
504,2011,NOR,Norway,7.50,1.71,34.20,5.09,18.53,8.0,18.97,...,1.0,4.35,4.05,2.05,9.74,8.47,8.86,9.02,7.03,7.13
505,2011,SWE,Sweden,7.50,1.29,35.60,4.70,19.96,8.0,19.55,...,10.0,6.66,4.99,1.28,9.44,8.52,8.89,8.63,6.96,7.87
506,2011,KOR,"Korea, South",7.48,5.00,23.00,8.35,6.55,8.0,16.31,...,0.0,4.67,3.22,3.81,9.62,5.35,9.77,7.68,6.58,6.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2011,NER,Niger,6.01,6.97,16.30,9.84,1.09,10.0,13.80,...,0.0,3.85,NaN,NaN,6.39,NaN,2.68,6.97,5.35,6.29
607,2011,SEN,Senegal,5.99,6.65,17.40,10.00,0.00,6.0,28.68,...,0.0,4.38,3.50,5.57,8.53,4.04,6.54,2.53,5.12,5.94
608,2011,BFA,Burkina Faso,5.95,4.24,25.60,9.95,0.69,2.0,41.80,...,10.0,7.82,4.54,6.40,7.93,3.55,8.63,6.97,6.34,7.63
609,2011,IRN,Iran,5.94,6.32,18.51,7.99,7.88,6.0,27.00,...,1.0,4.65,3.10,5.58,9.55,5.06,5.22,6.14,5.78,4.44
610,2011,MLI,Mali,5.91,5.38,21.71,9.93,0.76,2.0,45.07,...,0.0,5.50,4.20,6.43,7.75,2.46,7.24,6.97,5.84,6.51
611,2011,CIV,Cote d'Ivoire,5.86,7.57,14.27,9.68,1.68,8.0,16.20,...,1.0,5.72,4.22,7.03,7.00,3.50,4.72,6.97,5.57,6.39
612,2011,ECU,Ecuador,5.84,6.65,17.40,9.59,2.00,0.0,51.80,...,3.0,4.31,3.36,5.66,7.88,3.65,8.45,2.67,5.28,6.29
613,2011,MOZ,Mozambique,5.82,5.76,20.40,9.10,3.80,4.0,37.71,...,0.0,3.05,4.01,6.84,9.38,4.19,4.79,7.42,6.11,6.07
614,2011,GNB,Guinea-Bissau,5.74,7.86,13.29,NaN,NaN,2.0,44.36,...,0.0,3.46,NaN,NaN,8.16,NaN,6.84,7.67,7.56,7.00
615,2011,ARG,Argentina,5.67,6.53,17.80,5.76,16.07,6.0,NaN,...,10.0,5.34,2.42,5.60,9.02,2.95,4.87,5.46,5.05,5.74
616,2011,MRT,Mauritania,5.64,3.83,26.97,NaN,NaN,2.0,42.80,...,5.0,6.57,5.22,7.56,7.82,3.18,4.58,2.20,5.09,6.73
617,2011,GAB,Gabon,5.58,2.44,31.69,9.81,1.20,4.0,39.45,...,10.0,7.45,5.36,NaN,7.92,4.49,6.81,4.53,5.82,6.80
618,2011,TGO,Togo,5.45,8.79,10.10,10.00,0.00,2.0,44.57,...,0.0,4.17,NaN,NaN,6.33,NaN,5.10,6.97,6.13,5.93
619,2011,COD,"Congo, Dem. R.",5.43,7.82,13.40,8.85,4.72,4.0,39.60,...,3.0,5.67,NaN,NaN,5.15,NaN,6.15,6.23,5.84,5.73
620,2011,CAF,Central Afr. Rep.,5.32,9.41,8.00,9.53,2.21,4.0,32.06,...,0.0,3.44,NaN,NaN,6.03,NaN,7.26,4.35,5.88,5.55
621,2011,BDI,Burundi,5.30,4.74,23.90,9.49,2.37,0.0,56.50,...,10.0,7.69,2.94,7.58,9.55,2.24,5.84,6.93,5.85,7.02
622,2011,ETH,Ethiopia,5.21,8.09,12.50,8.65,5.45,0.0,73.01,...,10.0,7.45,4.06,6.11,7.28,3.80,8.33,6.57,6.03,6.34
623,2011,DZA,Algeria,5.20,0.03,39.90,7.82,8.51,0.0,61.26,...,1.0,4.87,2.13,6.52,8.98,2.62,6.24,4.94,5.24,5.47
624,2011,AGO,Angola,5.13,0.91,36.91,7.60,9.30,0.0,78.70,...,0.0,3.07,1.76,7.94,6.64,2.89,4.96,6.84,5.17,5.64
625,2011,TCD,Chad,5.07,8.68,10.49,9.92,0.80,4.0,33.80,...,3.0,6.23,3.45,6.97,4.94,2.25,3.41,1.79,3.80,5.44
626,2011,ZWE,Zimbabwe,4.99,7.06,16.00,7.75,8.77,8.0,15.70,...,10.0,4.29,3.30,5.78,5.99,4.52,0.00,7.29,4.48,4.52
627,2011,COG,"Congo, Rep. Of",4.57,5.26,22.10,10.00,0.47,0.0,63.56,...,10.0,6.48,NaN,NaN,5.82,NaN,5.56,3.21,4.86,5.89
628,2011,MMR,Myanmar,4.24,8.01,12.77,NaN,NaN,4.0,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.48
629,2011,VEN,Venezuela,3.96,6.68,17.30,5.77,16.01,0.0,60.59,...,0.0,3.51,1.84,5.66,6.38,2.53,4.78,1.12,3.72,4.57
630,2011,BTN,Bhutan,NaN,2.18,32.60,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
631,2011,GIN,Guinea,NaN,8.68,10.50,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,2011,LAO,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
633,2011,LBR,Liberia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
634,2011,LBY,Libya,NaN,0.00,46.62,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
635,2011,SYC,Seychelles,NaN,2.35,32.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
economic_freedom_df = economic_freedom_raw_df[economic_freedom_raw_df['Year'].between(min(years), max(years))][
        ["ISO_Code", "Countries", "Year", "Economic Freedom Summary Index"]].rename(columns={
            "ISO_Code": "Country Code",
            "Countries": "Country Name",
            "Economic Freedom Summary Index": "Economic Freedom Index"})

economic_freedom_df.head()

  Country Code Country Name  Year  Economic Freedom Index
0          HKG    Hong Kong  2014                    9.03
1          SGP    Singapore  2014                    8.71
2          NZL  New Zealand  2014                    8.35
3          CHE  Switzerland  2014                    8.25
4          CAN       Canada  2014                    7.98

## Democracy Index from Economist Business Unit

In [10]:
democracy_df = pd.read_csv("./democracy_index_from_wikipedia/democracy_index_2016.csv")

democracy_df.head()

,position,country_name,flag_uri,score,electoral_process_and_pluralism,functioning_of_government,political_participation,political_culture,civil_liberties,category
0,1,Norway,//upload.wikimedia.org/wikipedia/commons/thumb...,9.93,10.00,9.64,10.00,10.00,10.00,Full democracy
1,2,Iceland,//upload.wikimedia.org/wikipedia/commons/thumb...,9.50,10.00,8.93,8.89,10.00,9.71,Full democracy
2,3,Sweden,//upload.wikimedia.org/wikipedia/en/thumb/4/4c...,9.39,9.58,9.64,8.33,10.00,9.41,Full democracy
3,4,New Zealand,//upload.wikimedia.org/wikipedia/commons/thumb...,9.26,10.00,9.29,8.89,8.13,10.00,Full democracy
4,5,Denmark,//upload.wikimedia.org/wikipedia/commons/thumb...,9.20,9.58,9.29,8.33,9.38,9.41,Full democracy

In [11]:
democracy_df = democracy_df[["country_name", "score"]].rename(columns={"score": "democracy_score_2016"})

democracy_df.head()

  country_name  democracy_score_2016
0       Norway                  9.93
1      Iceland                  9.50
2       Sweden                  9.39
3  New Zealand                  9.26
4      Denmark                  9.20

In [12]:
from os import listdir

In [13]:
import os.path as path

In [14]:
indexes_dir = "scrapped_democracy_indexes_from_econominst_bu"

listdir(indexes_dir)

['democracy_index_2014.csv',
 'democracy_index_2012.csv',
 'democracy_index_2015.csv',
 'sha512sums.txt',
 'democracy_index_2013.csv',
 'democracy_index_2011.csv']

In [15]:
democracy_index_years = range(2011, (2015 + 1)) # Used +1 to indicate that the last year is 2015

In [16]:
for year in democracy_index_years:
    # print(year)
    target_file_location = path.join(indexes_dir, ("democracy_index_%s.csv" % year))
    # print(target_file_location)
    current_year_df = pd.read_csv(target_file_location)
    current_year_df = current_year_df[["Country", "Overall Score"]].rename(columns={
        "Country": "country_name_RIGHT",
        "Overall Score": ("democracy_score_%s" % year)
    })
    # print(current_year_df.head())
    # Le Mergé:
    democracy_df = pd.merge(democracy_df, current_year_df,
                            how="inner",
                            left_on="country_name",
                            right_on="country_name_RIGHT")
    del democracy_df['country_name_RIGHT']
    # print(democracy_df.head())

In [17]:
democracy_df.head()

,country_name,democracy_score_2016,democracy_score_2011,democracy_score_2012,democracy_score_2013,democracy_score_2014,democracy_score_2015
0,Norway,9.93,9.80,9.93,9.93,9.93,9.93
1,Iceland,9.50,9.65,9.65,9.65,9.58,9.58
2,Sweden,9.39,9.50,9.73,9.73,9.73,9.45
3,New Zealand,9.26,9.26,9.26,9.26,9.26,9.26
4,Denmark,9.20,9.52,9.52,9.38,9.11,9.11

## Mega-Merge

In [18]:
len(democracy_df)

161

In [19]:
len(economic_freedom_df)

159

In [20]:
len(world_gdp_df)

264

In [21]:
project_df_part = pd.merge(world_gdp_df, economic_freedom_df, how="inner",
                      left_on="country_code", right_on="economic_freedom_country_code")

del project_df_part['economic_freedom_country_code']
del project_df_part['economic_freedom_country_name']
# project_df_part.columns
project_df_part.head()

,country_name,country_code,gdp_2004,gdp_2005,gdp_2006,gdp_2007,gdp_2008,gdp_2009,gdp_2010,gdp_2011,...,economic_freedom_index_2005,economic_freedom_index_2006,economic_freedom_index_2007,economic_freedom_index_2008,economic_freedom_index_2009,economic_freedom_index_2010,economic_freedom_index_2011,economic_freedom_index_2012,economic_freedom_index_2013,economic_freedom_index_2014
0,Angola,AGO,1041.086844,1443.991929,2062.415149,2878.837144,3868.578883,3347.844850,3529.053482,4299.012889,...,3.81,4.43,4.58,4.43,5.19,5.26,5.13,5.32,5.21,5.08
1,Albania,ALB,2416.588235,2709.142931,3005.012903,3603.013685,4370.539647,4114.136545,4094.358832,4437.178068,...,6.98,7.16,7.23,7.24,7.32,7.37,7.25,7.21,7.27,7.40
2,United Arab Emirates,ARE,36161.170607,39439.801968,42372.221662,42672.613229,45758.905536,33072.575166,35049.148317,40462.312090,...,7.71,7.87,7.96,7.99,7.72,7.91,8.06,8.08,8.11,7.98
3,Argentina,ARG,4251.574348,5076.883829,5878.761027,7193.617640,8953.359275,8161.306966,10276.260498,12726.908359,...,5.99,6.11,6.22,6.01,5.97,5.74,5.67,5.15,5.01,4.81
4,Armenia,ARM,1191.961920,1643.758397,2158.002909,3138.808703,4010.026997,2993.832531,3218.381655,3526.978143,...,7.31,7.46,7.43,7.60,7.56,7.55,7.71,7.75,7.70,7.71

In [22]:
project_df = pd.merge(project_df_part, democracy_df, how="inner",
                      left_on="country_name", right_on="country_name")

project_df.head()

,country_name,country_code,gdp_2004,gdp_2005,gdp_2006,gdp_2007,gdp_2008,gdp_2009,gdp_2010,gdp_2011,...,economic_freedom_index_2011,economic_freedom_index_2012,economic_freedom_index_2013,economic_freedom_index_2014,democracy_score_2016,democracy_score_2011,democracy_score_2012,democracy_score_2013,democracy_score_2014,democracy_score_2015
0,Angola,AGO,1041.086844,1443.991929,2062.415149,2878.837144,3868.578883,3347.844850,3529.053482,4299.012889,...,5.13,5.32,5.21,5.08,3.40,3.32,3.35,3.35,3.35,3.35
1,Albania,ALB,2416.588235,2709.142931,3005.012903,3603.013685,4370.539647,4114.136545,4094.358832,4437.178068,...,7.25,7.21,7.27,7.40,5.91,5.81,5.67,5.67,5.67,5.91
2,United Arab Emirates,ARE,36161.170607,39439.801968,42372.221662,42672.613229,45758.905536,33072.575166,35049.148317,40462.312090,...,8.06,8.08,8.11,7.98,2.75,2.58,2.58,2.52,2.64,2.75
3,Argentina,ARG,4251.574348,5076.883829,5878.761027,7193.617640,8953.359275,8161.306966,10276.260498,12726.908359,...,5.67,5.15,5.01,4.81,6.96,6.84,6.84,6.84,6.84,7.02
4,Armenia,ARM,1191.961920,1643.758397,2158.002909,3138.808703,4010.026997,2993.832531,3218.381655,3526.978143,...,7.71,7.75,7.70,7.71,3.88,4.09,4.09,4.02,4.13,4.00

In [23]:
project_df.to_csv("project_data.csv", encoding='utf-8', index=False)