In [1]:
import pandas as pd

# Import to data frames

## GPD per capita from World Bank

In [2]:
world_gdp_df = pd.read_csv("./gdp_from_world_bank/API_NY.GDP.PCAP.CD_DS2_en_csv_v2.csv", skiprows=4)

world_gdp_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,Unnamed: 61
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27546.899390,24631.434860,24271.940421,25324.720362,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,59.777327,59.878153,58.492874,78.782758,82.208444,101.290471,...,373.361116,445.893298,553.300289,603.537023,669.009051,631.744971,612.069651,584.025902,561.778746,NaN
2,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3868.578883,3347.844850,3529.053482,4299.012889,4598.249988,4804.616884,4709.312024,3695.793748,3110.808183,NaN
3,Albania,ALB,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4370.539647,4114.136545,4094.358832,4437.178068,4247.614308,4414.723140,4575.763787,3954.022783,4146.896250,NaN
4,Andorra,AND,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,47712.299081,43215.687013,39627.663516,40919.183279,38167.095746,40215.435317,NaN,NaN,NaN,NaN

## Economic Freedom from Frazer institute

In [3]:
economic_freedom_df = pd.read_csv("./frazer_institute_economic_freedom/economic-freedom-of-the-world-data-for-researchers.csv")

economic_freedom_df.head()

,Year,ISO_Code,Countries,Economic Freedom Summary Index,Government Consumption,1A data,Transfers and subsidies,1B data,Government enterprises and investment,1C data,...,Conscription,Labor market regulations,Administrative requirements,Bureaucracy costs,Starting a business,Extra payments/bribes/favoritism,Licensing restrictions,Tax compliance,Business regulations,Regulation
0,2014,HKG,Hong Kong,9.03,8.08,12.54,9.17,3.55,10.0,12.62,...,10.0,9.38,7.05,3.05,9.94,7.34,9.74,9.17,7.72,9.03
1,2014,SGP,Singapore,8.71,5.46,21.44,8.85,4.71,7.0,NaN,...,0.0,7.80,7.29,2.15,9.91,8.32,10.00,9.06,7.79,8.53
2,2014,NZL,New Zealand,8.35,4.40,25.05,6.17,14.56,8.0,16.66,...,10.0,8.48,4.76,2.04,9.98,8.45,9.40,8.30,7.15,8.51
3,2014,CHE,Switzerland,8.25,6.79,16.90,6.03,15.08,10.0,12.68,...,5.0,7.74,5.87,1.48,9.58,7.56,8.37,9.29,7.02,8.03
4,2014,CAN,Canada,7.98,3.68,27.50,7.61,9.26,8.0,16.24,...,10.0,8.14,4.73,2.02,9.95,6.72,6.86,8.53,6.47,8.11

## Economist's Business Unit Democracy Index from Wikipedia

In [4]:
democracy_df = pd.read_csv("./democracy_index_from_wikipedia/democracy_index_2016.csv")

democracy_df.head()

,position,country_name,flag_uri,score,electoral_process_and_pluralism,functioning_of_government,political_participation,political_culture,civil_liberties,category
0,1,Norway,//upload.wikimedia.org/wikipedia/commons/thumb...,9.93,10.00,9.64,10.00,10.00,10.00,Full democracy
1,2,Iceland,//upload.wikimedia.org/wikipedia/commons/thumb...,9.50,10.00,8.93,8.89,10.00,9.71,Full democracy
2,3,Sweden,//upload.wikimedia.org/wikipedia/en/thumb/4/4c...,9.39,9.58,9.64,8.33,10.00,9.41,Full democracy
3,4,New Zealand,//upload.wikimedia.org/wikipedia/commons/thumb...,9.26,10.00,9.29,8.89,8.13,10.00,Full democracy
4,5,Denmark,//upload.wikimedia.org/wikipedia/commons/thumb...,9.20,9.58,9.29,8.33,9.38,9.41,Full democracy

# Extract only necessary data and join

In [5]:
gdp_subset_df = world_gdp_df[["Country Name", "Country Code", "2016"]].rename(columns={
    'Country Name': 'per_capita_country_name',
    'Country Code': 'per_capita_country_code',
    '2016': 'per_capita_income'})
gdp_subset_df.dropna(inplace=True)

gdp_subset_df.head()

  per_capita_country_name per_capita_country_code  per_capita_income
1             Afghanistan                     AFG         561.778746
2                  Angola                     AGO        3110.808183
3                 Albania                     ALB        4146.896250
5              Arab World                     ARB        6153.069547
6    United Arab Emirates                     ARE       37622.207458

In [6]:
democracy_subset_df = democracy_df[["country_name", "score"]].rename(columns={
    "country_name": "democracy_country_name",
    "score": "democracy_score",
})

democracy_subset_df.head()

  democracy_country_name  democracy_score
0                 Norway             9.93
1                Iceland             9.50
2                 Sweden             9.39
3            New Zealand             9.26
4                Denmark             9.20

In [7]:
economic_freedom_subset_df = economic_freedom_df[economic_freedom_df["Year"] == 2014][
    ["ISO_Code", "Countries", "Economic Freedom Summary Index"]].rename(columns={
        "ISO_Code": "economic_freedom_country_code",
        "Countries": "economic_freedom_country_name",
        "Economic Freedom Summary Index": "economic_freedom_index"
    })

economic_freedom_subset_df.head()

,economic_freedom_country_code,economic_freedom_country_name,economic_freedom_index
0,HKG,Hong Kong,9.03
1,SGP,Singapore,8.71
2,NZL,New Zealand,8.35
3,CHE,Switzerland,8.25
4,CAN,Canada,7.98

... and join

In [8]:
freedom_and_gdp_df = pd.merge(economic_freedom_subset_df, gdp_subset_df, how='inner',
         left_on=["economic_freedom_country_code", "economic_freedom_country_name"],
         right_on=["per_capita_country_code", "per_capita_country_name"]
        )

In [9]:
len(freedom_and_gdp_df)

134

In [10]:
final_df = pd.merge(freedom_and_gdp_df, democracy_subset_df, how='inner',
                    left_on="economic_freedom_country_name", right_on="democracy_country_name")

In [11]:
final_df

,economic_freedom_country_code,economic_freedom_country_name,economic_freedom_index,per_capita_country_name,per_capita_country_code,per_capita_income,democracy_country_name,democracy_score
0,SGP,Singapore,8.71,Singapore,SGP,52960.714189,Singapore,6.38
1,NZL,New Zealand,8.35,New Zealand,NZL,39426.623499,New Zealand,9.26
2,CHE,Switzerland,8.25,Switzerland,CHE,78812.650687,Switzerland,9.09
3,CAN,Canada,7.98,Canada,CAN,42157.927991,Canada,9.15
4,GEO,Georgia,7.98,Georgia,GEO,3853.649904,Georgia,5.93
5,IRL,Ireland,7.98,Ireland,IRL,61606.482939,Ireland,9.15
6,MUS,Mauritius,7.98,Mauritius,MUS,9627.595785,Mauritius,8.28
7,AUS,Australia,7.93,Australia,AUS,49927.819509,Australia,9.01
8,GBR,United Kingdom,7.93,United Kingdom,GBR,39899.388395,United Kingdom,8.36
9,QAT,Qatar,7.91,Qatar,QAT,59330.859987,Qatar,3.18
10,CHL,Chile,7.83,Chile,CHL,13792.926054,Chile,7.78
11,JOR,Jordan,7.82,Jordan,JOR,4087.937517,Jordan,3.96
12,LTU,Lithuania,7.81,Lithuania,LTU,14879.680299,Lithuania,7.47
13,USA,United States,7.75,United States,USA,57466.787113,United States,7.98
14,MLT,Malta,7.74,Malta,MLT,25058.170606,Malta,8.39
15,ARM,Armenia,7.71,Armenia,ARM,3606.152057,Armenia,3.88
16,EST,Estonia,7.70,Estonia,EST,17574.687355,Estonia,7.85
17,FIN,Finland,7.68,Finland,FIN,43090.247506,Finland,9.03
18,DNK,Denmark,7.67,Denmark,DNK,53417.664276,Denmark,9.20
19,ROU,Romania,7.66,Romania,ROU,9474.130604,Romania,6.62
20,LUX,Luxembourg,7.65,Luxembourg,LUX,102831.321483,Luxembourg,8.81
21,NLD,Netherlands,7.63,Netherlands,NLD,45294.779995,Netherlands,8.80
22,BHR,Bahrain,7.60,Bahrain,BHR,22354.167071,Bahrain,2.79
23,LVA,Latvia,7.57,Latvia,LVA,14118.063907,Latvia,7.31
24,AUT,Austria,7.56,Austria,AUT,44176.515216,Austria,8.41
25,CRI,Costa Rica,7.56,Costa Rica,CRI,11824.638102,Costa Rica,7.88
26,DEU,Germany,7.55,Germany,DEU,41936.058575,Germany,8.63
27,BEL,Belgium,7.51,Belgium,BEL,41096.157302,Belgium,7.77
28,NOR,Norway,7.51,Norway,NOR,70812.477423,Norway,9.93
29,GTM,Guatemala,7.50,Guatemala,GTM,4146.744129,Guatemala,5.92
...,...,...,...,...,...,...,...,...
97,SEN,Senegal,6.42,Senegal,SEN,958.073738,Senegal,6.21
98,GHA,Ghana,6.41,Ghana,GHA,1513.461034,Ghana,6.75
99,BGD,Bangladesh,6.35,Bangladesh,BGD,1358.779752,Bangladesh,5.73
100,BOL,Bolivia,6.34,Bolivia,BOL,3104.956089,Bolivia,5.63
101,BRA,Brazil,6.27,Brazil,BRA,8649.948492,Brazil,6.90
102,CMR,Cameroon,6.25,Cameroon,CMR,1032.648722,Cameroon,3.46
103,BEN,Benin,6.22,Benin,BEN,789.440411,Benin,5.67
104,GNB,Guinea-Bissau,6.08,Guinea-Bissau,GNB,620.214765,Guinea-Bissau,1.98
105,BDI,Burundi,6.05,Burundi,BDI,285.727442,Burundi,2.40
106,NER,Niger,6.05,Niger,NER,363.226974,Niger,3.96
107,BFA,Burkina Faso,6.02,Burkina Faso,BFA,649.730484,Burkina Faso,4.70
108,PAK,Pakistan,6.01,Pakistan,PAK,1468.192946,Pakistan,4.33
109,UKR,Ukraine,6.00,Ukraine,UKR,2185.728031,Ukraine,5.70
110,GUY,Guyana,5.98,Guyana,GUY,4456.553697,Guyana,6.25
111,MLI,Mali,5.97,Mali,MLI,780.507111,Mali,5.70
112,SLE,Sierra Leone,5.92,Sierra Leone,SLE,496.049463,Sierra Leone,4.55
113,TGO,Togo,5.89,Togo,TGO,578.461694,Togo,3.32
114,MOZ,Mozambique,5.81,Mozambique,MOZ,382.069330,Mozambique,4.02
115,MWI,Malawi,5.79,Malawi,MWI,300.794825,Malawi,5.55
116,ECU,Ecuador,5.76,Ecuador,ECU,5968.984138,Ecuador,5.81
117,GAB,Gabon,5.71,Gabon,GAB,7179.340661,Gabon,3.74
118,MRT,Mauritania,5.63,Mauritania,MRT,1077.556136,Mauritania,3.96
119,ETH,Ethiopia,5.60,Ethiopia,ETH,706.757754,Ethiopia,3.60
120,MMR,Myanmar,5.39,Myanmar,MMR,1275.017608,Myanmar,4.20
121,ZWE,Zimbabwe,5.28,Zimbabwe,ZWE,1008.597331,Zimbabwe,3.05
122,DZA,Algeria,5.15,Algeria,DZA,3843.752322,Algeria,3.56
123,TCD,Chad,5.12,Chad,TCD,664.295652,Chad,1.50
124,GIN,Guinea,5.10,Guinea,GIN,508.145078,Guinea,3.14
125,AGO,Angola,5.08,Angola,AGO,3110.808183,Angola,3.40
126,ARG,Argentina,4.81,Argentina,ARG,12449.216852,Argentina,6.96

### Drop duplicate columns and rename

In [12]:
del final_df["per_capita_country_code"]
del final_df["per_capita_country_name"]

del final_df["democracy_country_name"]

In [13]:
final_df.rename({
    "economic_freedom_country_code": "country_code",
    "economic_freedom_country_name": "country_name"
}, inplace=True)

In [14]:
final_df

,economic_freedom_country_code,economic_freedom_country_name,economic_freedom_index,per_capita_income,democracy_score
0,SGP,Singapore,8.71,52960.714189,6.38
1,NZL,New Zealand,8.35,39426.623499,9.26
2,CHE,Switzerland,8.25,78812.650687,9.09
3,CAN,Canada,7.98,42157.927991,9.15
4,GEO,Georgia,7.98,3853.649904,5.93
5,IRL,Ireland,7.98,61606.482939,9.15
6,MUS,Mauritius,7.98,9627.595785,8.28
7,AUS,Australia,7.93,49927.819509,9.01
8,GBR,United Kingdom,7.93,39899.388395,8.36
9,QAT,Qatar,7.91,59330.859987,3.18
10,CHL,Chile,7.83,13792.926054,7.78
11,JOR,Jordan,7.82,4087.937517,3.96
12,LTU,Lithuania,7.81,14879.680299,7.47
13,USA,United States,7.75,57466.787113,7.98
14,MLT,Malta,7.74,25058.170606,8.39
15,ARM,Armenia,7.71,3606.152057,3.88
16,EST,Estonia,7.70,17574.687355,7.85
17,FIN,Finland,7.68,43090.247506,9.03
18,DNK,Denmark,7.67,53417.664276,9.20
19,ROU,Romania,7.66,9474.130604,6.62
20,LUX,Luxembourg,7.65,102831.321483,8.81
21,NLD,Netherlands,7.63,45294.779995,8.80
22,BHR,Bahrain,7.60,22354.167071,2.79
23,LVA,Latvia,7.57,14118.063907,7.31
24,AUT,Austria,7.56,44176.515216,8.41
25,CRI,Costa Rica,7.56,11824.638102,7.88
26,DEU,Germany,7.55,41936.058575,8.63
27,BEL,Belgium,7.51,41096.157302,7.77
28,NOR,Norway,7.51,70812.477423,9.93
29,GTM,Guatemala,7.50,4146.744129,5.92
...,...,...,...,...,...
97,SEN,Senegal,6.42,958.073738,6.21
98,GHA,Ghana,6.41,1513.461034,6.75
99,BGD,Bangladesh,6.35,1358.779752,5.73
100,BOL,Bolivia,6.34,3104.956089,5.63
101,BRA,Brazil,6.27,8649.948492,6.90
102,CMR,Cameroon,6.25,1032.648722,3.46
103,BEN,Benin,6.22,789.440411,5.67
104,GNB,Guinea-Bissau,6.08,620.214765,1.98
105,BDI,Burundi,6.05,285.727442,2.40
106,NER,Niger,6.05,363.226974,3.96
107,BFA,Burkina Faso,6.02,649.730484,4.70
108,PAK,Pakistan,6.01,1468.192946,4.33
109,UKR,Ukraine,6.00,2185.728031,5.70
110,GUY,Guyana,5.98,4456.553697,6.25
111,MLI,Mali,5.97,780.507111,5.70
112,SLE,Sierra Leone,5.92,496.049463,4.55
113,TGO,Togo,5.89,578.461694,3.32
114,MOZ,Mozambique,5.81,382.069330,4.02
115,MWI,Malawi,5.79,300.794825,5.55
116,ECU,Ecuador,5.76,5968.984138,5.81
117,GAB,Gabon,5.71,7179.340661,3.74
118,MRT,Mauritania,5.63,1077.556136,3.96
119,ETH,Ethiopia,5.60,706.757754,3.60
120,MMR,Myanmar,5.39,1275.017608,4.20
121,ZWE,Zimbabwe,5.28,1008.597331,3.05
122,DZA,Algeria,5.15,3843.752322,3.56
123,TCD,Chad,5.12,664.295652,1.50
124,GIN,Guinea,5.10,508.145078,3.14
125,AGO,Angola,5.08,3110.808183,3.40
126,ARG,Argentina,4.81,12449.216852,6.96